Failure # 1 (occurred at 2024-06-13_04-31-20)
[36mray::SimpleQ.train()[39m (pid=3207886, ip=192.168.210.211, repr=SimpleQ)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/simple_q/simple_q_torch_policy.py", line 125, in loss
    q_tp1 = self._compute_q_values(
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/simple_q/simple_q_torch_policy.py", line 184, in _compute_q_values
    model_out, _ = model(input_dict, [], None)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/models/modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/model.py", line 200, in forward
    temp = self.conv9_6(temp) + res9_2
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/model.py", line 30, in forward
    return self.convrelu(x)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 4522, in pad
    return torch._C._nn.pad(input, pad, mode, value)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 

The above exception was the direct cause of the following exception:

[36mray::SimpleQ.train()[39m (pid=3207886, ip=192.168.210.211, repr=SimpleQ)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 352, in train
    result = self.step()
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 772, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2953, in _run_one_training_iteration
    num_recreated += self.try_recover_from_step_attempt(
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2622, in try_recover_from_step_attempt
    raise error
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2948, in _run_one_training_iteration
    results = self.training_step()
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/simple_q/simple_q.py", line 372, in training_step
    train_results = multi_gpu_train_one_step(self, train_batch)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/execution/train_ops.py", line 176, in multi_gpu_train_one_step
    results = policy.learn_on_loaded_batch(
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 742, in learn_on_loaded_batch
    tower_outputs = self._multi_gpu_parallel_grad_calc(device_batches)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1191, in _multi_gpu_parallel_grad_calc
    raise last_result[0] from last_result[1]
ValueError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 
 tracebackTraceback (most recent call last):
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1107, in _worker
    self.loss(model, self.dist_class, sample_batch)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/simple_q/simple_q_torch_policy.py", line 125, in loss
    q_tp1 = self._compute_q_values(
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/algorithms/simple_q/simple_q_torch_policy.py", line 184, in _compute_q_values
    model_out, _ = model(input_dict, [], None)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/ray/rllib/models/modelv2.py", line 259, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/model.py", line 200, in forward
    temp = self.conv9_6(temp) + res9_2
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/model.py", line 30, in forward
    return self.convrelu(x)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/home/anthony/meent/examples/applications/metasurface-design/dqn/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 4522, in pad
    return torch._C._nn.pad(input, pad, mode, value)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 

In tower 0 on device cuda:0
